### ISSUE TITLE
 module 'kornia' has no attribute 'adjust_brightness'

### ISSUE THREAD

**Issue by bohniti** [anguelos/tormentor#4]
The module has moved from kornia to kornia.enhance (https://kornia.readthedocs.io/en/latest/enhance.html).
Could be fixed by specifying an older version in the requirements or by changing the import statement. 

If could make a pull request if that makes your life easier. :)

**Comment by anguelos** [comment]
I Believe I corrected all problems arising from this kornia namespace refactoring in my last merge.
